/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pszak' at '2/1/16 11:06 AM' with Gradle 2.8
 *
 * @author pszak, @date 2/1/16 11:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    String myNameIs() {
        return null;
    }
}
